language: node_js

node_js:
  - "6"

install:
  - npm install

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  - "./node_modules/.bin/selenium-standalone start --silent &"
  - sleep 3 # give selenium some time to start
